:pidfile: tmp/pids/sidekiq.pid
:timeout: 15
development:
  :concurrency: 15
  :logfile: ./log/sidekiq_development.log
production:
  :concurrency: 15
  :logfile: ./log/sidekiq_production.log
:queues:
  - [rails_react, 1]
  - default